name: Documenter
on:
  push:
    branches: [main, release-*]
    tags: [v*]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - release-*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Documenter:
    name: Documentation
    # Run on push's or non-draft PRs
    if: (github.event_name == 'push') || (github.event.pull_request.draft == false)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/julia-buildpkg@latest
      - name: Cache
        uses: julia-actions/cache@v2
        with:
            cache-compiled: "true"
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
